# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install: 
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = T)'
apt_packages:
  - libgdal1-dev
  - gdal-bin
  - libproj-dev
  - proj-data
  - proj-bin 
  - libgeos-dev
  - libudunits2-dev
